#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;

use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../../lib";

use V6::Beanstalk;
use V6::DB;

my $beanstalk = V6::Beanstalk->new;
$beanstalk->watch('v6-results');

my $coll = V6::DB->collection;
while (my $job = $beanstalk->reserve) {
    my %data = %{ $job->args };
    my $id   = eval{ $coll->insert(\%data) };
    my $err = $db->last_error;
    if ($err && !$err->{ok}) {
        warn Data::Dumper->Dump([\$err], [qw(err)]);
    }
    if ($id) {
        $job->delete;
    }
    else {
        $job->release({ delay => 60 });
    }
}

1;
