#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;

use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../../lib";

use V6::DB;
use V6::Beanstalk;
use V6::Summarizer;

use Log::Dispatch;
use JSON::XS ();
use File::Path qw(mkpath);

my $JSON = JSON::XS->new->relaxed(1);

my $beanstalk = V6::Beanstalk->new;
$beanstalk->watch('v6-results');

my $logs = "$FindBin::Bin/../logs";
mkpath $logs unless -e $logs;

my $log = Log::Dispatch->new(
    outputs => [ [ 'File::Stamped',
                   name        => 'data',
                   filename    => '$logs/data.log',
                   min_level   => 'info',
                   mode        => 'append',
                   stamp_fmt   => '%Y%m',
                   newline     => 1,
                 ]
    ],
);

my $summ = V6::Summarizer->new;

while (my $job = $beanstalk->reserve) {
    my $data = $job->args;
    $log->info($JSON->encode($data));
    $summ->process_entry($data);
}

1;
