#!/bin/sh

if [ `uname -s` == 'Darwin' ]; then
  STAT_FORMAT='-f "%Y"'
else
  STAT_FORMAT='--printf="%Y"'
fi

STAT_T=`stat $STAT_FORMAT public/js/v1/v6test.js 2> /dev/null`
STAT_S=`stat $STAT_FORMAT public/devel/v6test.js`

if [ "x$STAT_GZIP" != "x$STAT_ORIG" ]; then
   cat public/devel/jquery-cookie-2.1.js public/devel/v6test.js \
      | ./script/yuicompressor --type js \
      > public/js/v1/v6test.js
   touch -c -m -r public/devel/v6test.js public/js/v1/v6test.js
fi

./script/compress_static_files

