#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;

use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../../lib";

use V6::Beanstalk;
use V6::DB;
use Log::Dispatch;
use JSON::XS ();

my $JSON = JSON::XS->new->relaxed(1)->allow_blessed(1);

my $beanstalk = V6::Beanstalk->new;
$beanstalk->watch('v6-results');

my $log = Log::Dispatch->new(
    outputs => [ [ 'File::Stamped',
                   name        => 'data',
                   filename    => 'data.log',
                   min_level   => 'info',
                   mode        => 'append',
                   stamp_fmt   => '%Y%m%d',
                   newline     => 1,
                 ]
    ],
);

my $db   = V6::DB->mongodb;
my $coll = V6::DB->collection('results');
my $cursor = $coll->query({}, { sort_by => { _id => 1 } } );

my $i = 0;

while (my $data = $cursor->next) {
    $log->info($JSON->encode($data));
    #$summ->process_entry($data);
}

