#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;

use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../../lib";

use V6::DB;
use V6::Summarizer;

my $summ = V6::Summarizer->new;

my $mdb  = V6::DB->mongodb;
my $coll = $mdb->get_collection('results');

$mdb->get_collection('counts')->ensure_index
  ({ site => 1, year => 1, month => 1, country => 1 });

$mdb->get_collection('counts_daily')->ensure_index
  ({ site => 1, date => 1, country => 1 });

my $cursor = $coll->query({}, { sort_by => { _id => 1 } } );

my $i = 0;

while (my $data = $cursor->next) {
    $summ->process_entry($data);
}

