#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;

use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../../lib";

use V6::DB;
use V6::Summarizer;
use JSON::XS ();

my $JSON = JSON::XS->new->relaxed(1)->allow_blessed(1);

my $summ = V6::Summarizer->new;

my $mdb  = V6::DB->mongodb;

$mdb->get_collection('counts')->ensure_index
  ({ site => 1, year => 1, month => 1, country => 1 });

$mdb->get_collection('counts_daily')->ensure_index
  ({ site => 1, date => 1, country => 1 });


while (my $line = <>) {
    my $data = $JSON->decode($line);
    $summ->process_entry($data);
}

