#!/bin/sh

ulimit -v 4000000

VERSION=2.4.8
DIR=~/tmp/.yuicompressor
mkdir -p $DIR
JAR=$DIR/yuicompressor-$VERSION.jar
if [ ! -e $JAR ]; then
   mkdir -p $DIR
   curl -Lq -o $JAR.tmp http://mirrors.solfo.com/yuicompressor/yuicompressor-$VERSION.jar && \
   mv $JAR.tmp $JAR
fi

java -Xmx512m -jar $JAR \
  --charset utf-8 --line-break 100 --preserve-semi \
  $@


